In [36]:
import pandas as pd
from sklearn.preprocessing  import LabelEncoder, MinMaxScaler, StandardScaler
import seaborn as sns

In [37]:
studentData=pd.read_excel(r"C:\Users\vasun\Downloads\Practice_data.xlsx")

Inspect

In [38]:
studentData.sample(5)

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
27,1020,CSE,Male,89.0,7.5,81.0,9.0,86
12,1013,ECE,Female,74.0,5.0,63.0,7.0,69
24,1025,BBA,Female,73.0,4.2,57.0,6.0,63
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70
8,1009,AI&DS,Female,79.0,6.0,66.0,8.0,73

In [39]:
studentData.head(5)

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78
1,1002,IT,Female,91.0,8.2,74.0,10.0,86
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70
3,1004,AI&DS,Female,88.0,7.0,79.0,9.0,84
4,1005,BBA,Female,72.0,4.0,58.0,6.0,64

In [40]:
studentData.tail(5)

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
23,1024,CSE,Male,77.0,5.2,64.0,7.0,71
24,1025,BBA,Female,73.0,4.2,57.0,6.0,63
25,1006,CSE,Male,95.0,9.0,88.0,10.0,94
26,1012,IT,Male,87.0,7.8,76.0,9.0,83
27,1020,CSE,Male,89.0,7.5,81.0,9.0,86

Seperating

In [41]:
X=studentData.drop("Final_Score",axis=1)
print(X)

    Student_ID Department  Gender  Attendance_Pct  Study_Hours_Per_Day  \
0         1001        CSE    Male            82.0                  7.5
1         1002         IT  Female            91.0                  8.2
2         1003        ECE    Male            76.0                  5.5
3         1004      AI&DS  Female            88.0                  7.0
4         1005        BBA  Female            72.0                  4.0
5         1006        CSE    Male            95.0                  9.0
6         1007         IT  Female            67.0                  3.5
7         1008        ECE    Male            84.0                  6.5
8         1009      AI&DS  Female            79.0                  6.0
9         1010        CSE  Female            93.0                  8.5
10        1011        BBA    Male            69.0                  4.5
11        1012         IT    Male            87.0                  7.8
12        1013        ECE  Female            74.0                  5.0
13        1014      AI&DS    Male            90.0                  8.0
14        1015        CSE  Female            81.0                  NaN
15        1016         IT    Male            78.0                  5.8
16        1017        ECE  Female             NaN                  6.2
17        1018      AI&DS    Male            86.0                  7.2
18        1019        BBA  Female            65.0                  3.0
19        1020        CSE    Male            89.0                  7.5
20        1021         IT  Female            83.0                  6.8
21        1022        ECE    Male            71.0                  4.8
22        1023      AI&DS  Female            94.0                  9.2
23        1024        CSE    Male            77.0                  5.2
24        1025        BBA  Female            73.0                  4.2
25        1006        CSE    Male            95.0                  9.0
26        1012         IT    Male            87.0                  7.8
27        1020        CSE    Male            89.0                  7.5

    Internal_Marks  Assignments_Completed
0             68.0                    9.0
1             74.0                   10.0
2             61.0                    7.0
3             79.0                    9.0
4             58.0                    6.0
5             88.0                   10.0
6             52.0                    5.0
7             70.0                    8.0
8             66.0                    8.0
9             82.0                   10.0
10            55.0                    6.0
11            76.0                    9.0
12            63.0                    7.0
13            85.0                    9.0
14            72.0                    8.0
15             NaN                    7.0
16            67.0                    8.0
17            73.0                    NaN
18            49.0                    5.0
19            81.0                    9.0
20            71.0                    8.0
21            59.0                    6.0
22            89.0                   10.0
23            64.0                    7.0
24            57.0                    6.0
25            88.0                   10.0
26            76.0                    9.0
27            81.0                    9.0

In [42]:
y=studentData["Final_Score"]
print(y)

0     78
1     86
2     70
3     84
4     64
5     94
6     59
7     77
8     73
9     90
10    62
11    83
12    69
13    88
14    79
15    72
16    75
17    82
18    55
19    86
20    80
21    66
22    96
23    71
24    63
25    94
26    83
27    86
Name: Final_Score, dtype: int64

Missing Values

In [43]:
studentData.isnull().sum()

Student_ID               0
Department               0
Gender                   0
Attendance_Pct           1
Study_Hours_Per_Day      1
Internal_Marks           1
Assignments_Completed    1
Final_Score              0
dtype: int64

In [44]:
studentData["Attendance_Pct"].median()

83.0

In [45]:
studentData["Attendance_Pct"]=studentData["Attendance_Pct"].fillna(studentData["Attendance_Pct"].median())

In [46]:
studentData["Study_Hours_Per_Day"].median()

6.8

In [47]:
studentData["Study_Hours_Per_Day"]=studentData["Study_Hours_Per_Day"].fillna(studentData["Study_Hours_Per_Day"].median())

In [48]:
studentData["Internal_Marks"].median()

71.0

In [49]:
studentData["Internal_Marks"]=studentData["Internal_Marks"].fillna(studentData["Internal_Marks"].median())

In [50]:
studentData["Assignments_Completed"].median()

8.0

In [51]:
studentData["Assignments_Completed"]=studentData["Assignments_Completed"].fillna(studentData["Assignments_Completed"].median())

In [52]:
studentData.isnull().sum()

Student_ID               0
Department               0
Gender                   0
Attendance_Pct           0
Study_Hours_Per_Day      0
Internal_Marks           0
Assignments_Completed    0
Final_Score              0
dtype: int64

Duplicate Values

In [53]:
studentData.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25     True
26     True
27     True
dtype: bool

In [54]:
studentCleanedData=studentData.drop_duplicates()

In [55]:
studentCleanedData

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78
1,1002,IT,Female,91.0,8.2,74.0,10.0,86
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70
3,1004,AI&DS,Female,88.0,7.0,79.0,9.0,84
4,1005,BBA,Female,72.0,4.0,58.0,6.0,64
5,1006,CSE,Male,95.0,9.0,88.0,10.0,94
6,1007,IT,Female,67.0,3.5,52.0,5.0,59
7,1008,ECE,Male,84.0,6.5,70.0,8.0,77
8,1009,AI&DS,Female,79.0,6.0,66.0,8.0,73
9,1010,CSE,Female,93.0,8.5,82.0,10.0,90
10,1011,BBA,Male,69.0,4.5,55.0,6.0,62
11,1012,IT,Male,87.0,7.8,76.0,9.0,83
12,1013,ECE,Female,74.0,5.0,63.0,7.0,69
13,1014,AI&DS,Male,90.0,8.0,85.0,9.0,88
14,1015,CSE,Female,81.0,6.8,72.0,8.0,79
15,1016,IT,Male,78.0,5.8,71.0,7.0,72
16,1017,ECE,Female,83.0,6.2,67.0,8.0,75
17,1018,AI&DS,Male,86.0,7.2,73.0,8.0,82
18,1019,BBA,Female,65.0,3.0,49.0,5.0,55
19,1020,CSE,Male,89.0,7.5,81.0,9.0,86
20,1021,IT,Female,83.0,6.8,71.0,8.0,80
21,1022,ECE,Male,71.0,4.8,59.0,6.0,66
22,1023,AI&DS,Female,94.0,9.2,89.0,10.0,96
23,1024,CSE,Male,77.0,5.2,64.0,7.0,71
24,1025,BBA,Female,73.0,4.2,57.0,6.0,63

Encoding Categorical Data

In [56]:
encoder=LabelEncoder()
studentCleanedData["Gender_Encoded"]=encoder.fit_transform(studentCleanedData["Gender"])
studentCleanedData

C:\Users\vasun\AppData\Local\Temp\ipykernel_56364\1460029562.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  studentCleanedData["Gender_Encoded"]=encoder.fit_transform(studentCleanedData["Gender"])

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,Gender_Encoded
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78,1
1,1002,IT,Female,91.0,8.2,74.0,10.0,86,0
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70,1
3,1004,AI&DS,Female,88.0,7.0,79.0,9.0,84,0
4,1005,BBA,Female,72.0,4.0,58.0,6.0,64,0
5,1006,CSE,Male,95.0,9.0,88.0,10.0,94,1
6,1007,IT,Female,67.0,3.5,52.0,5.0,59,0
7,1008,ECE,Male,84.0,6.5,70.0,8.0,77,1
8,1009,AI&DS,Female,79.0,6.0,66.0,8.0,73,0
9,1010,CSE,Female,93.0,8.5,82.0,10.0,90,0
10,1011,BBA,Male,69.0,4.5,55.0,6.0,62,1
11,1012,IT,Male,87.0,7.8,76.0,9.0,83,1
12,1013,ECE,Female,74.0,5.0,63.0,7.0,69,0
13,1014,AI&DS,Male,90.0,8.0,85.0,9.0,88,1
14,1015,CSE,Female,81.0,6.8,72.0,8.0,79,0
15,1016,IT,Male,78.0,5.8,71.0,7.0,72,1
16,1017,ECE,Female,83.0,6.2,67.0,8.0,75,0
17,1018,AI&DS,Male,86.0,7.2,73.0,8.0,82,1
18,1019,BBA,Female,65.0,3.0,49.0,5.0,55,0
19,1020,CSE,Male,89.0,7.5,81.0,9.0,86,1
20,1021,IT,Female,83.0,6.8,71.0,8.0,80,0
21,1022,ECE,Male,71.0,4.8,59.0,6.0,66,1
22,1023,AI&DS,Female,94.0,9.2,89.0,10.0,96,0
23,1024,CSE,Male,77.0,5.2,64.0,7.0,71,1
24,1025,BBA,Female,73.0,4.2,57.0,6.0,63,0

In [57]:
studentCleanedData=pd.get_dummies(studentCleanedData,columns=["Department"])

In [58]:
studentCleanedData

,Student_ID,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,Gender_Encoded,Department_AI&DS,Department_BBA,Department_CSE,Department_ECE,Department_IT
0,1001,Male,82.0,7.5,68.0,9.0,78,1,False,False,True,False,False
1,1002,Female,91.0,8.2,74.0,10.0,86,0,False,False,False,False,True
2,1003,Male,76.0,5.5,61.0,7.0,70,1,False,False,False,True,False
3,1004,Female,88.0,7.0,79.0,9.0,84,0,True,False,False,False,False
4,1005,Female,72.0,4.0,58.0,6.0,64,0,False,True,False,False,False
5,1006,Male,95.0,9.0,88.0,10.0,94,1,False,False,True,False,False
6,1007,Female,67.0,3.5,52.0,5.0,59,0,False,False,False,False,True
7,1008,Male,84.0,6.5,70.0,8.0,77,1,False,False,False,True,False
8,1009,Female,79.0,6.0,66.0,8.0,73,0,True,False,False,False,False
9,1010,Female,93.0,8.5,82.0,10.0,90,0,False,False,True,False,False
10,1011,Male,69.0,4.5,55.0,6.0,62,1,False,True,False,False,False
11,1012,Male,87.0,7.8,76.0,9.0,83,1,False,False,False,False,True
12,1013,Female,74.0,5.0,63.0,7.0,69,0,False,False,False,True,False
13,1014,Male,90.0,8.0,85.0,9.0,88,1,True,False,False,False,False
14,1015,Female,81.0,6.8,72.0,8.0,79,0,False,False,True,False,False
15,1016,Male,78.0,5.8,71.0,7.0,72,1,False,False,False,False,True
16,1017,Female,83.0,6.2,67.0,8.0,75,0,False,False,False,True,False
17,1018,Male,86.0,7.2,73.0,8.0,82,1,True,False,False,False,False
18,1019,Female,65.0,3.0,49.0,5.0,55,0,False,True,False,False,False
19,1020,Male,89.0,7.5,81.0,9.0,86,1,False,False,True,False,False
20,1021,Female,83.0,6.8,71.0,8.0,80,0,False,False,False,False,True
21,1022,Male,71.0,4.8,59.0,6.0,66,1,False,False,False,True,False
22,1023,Female,94.0,9.2,89.0,10.0,96,0,True,False,False,False,False
23,1024,Male,77.0,5.2,64.0,7.0,71,1,False,False,True,False,False
24,1025,Female,73.0,4.2,57.0,6.0,63,0,False,True,False,False,False

In [ ]:
scaler=MinMaxScaler()
std_scaler=StandardScaler()
studentCleanedData["Attendance_Pct_scaled"]=scaler.fit_transform(studentCleanedData[["Attendance_Pct"]])
studentCleanedData[""]
studentCleanedData

,Student_ID,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,Gender_Encoded,Department_AI&DS,Department_BBA,Department_CSE,Department_ECE,Department_IT,Attendance_Pct_scaled
0,1001,Male,82.0,7.5,68.0,9.0,78,1,False,False,True,False,False,0.566667
1,1002,Female,91.0,8.2,74.0,10.0,86,0,False,False,False,False,True,0.866667
2,1003,Male,76.0,5.5,61.0,7.0,70,1,False,False,False,True,False,0.366667
3,1004,Female,88.0,7.0,79.0,9.0,84,0,True,False,False,False,False,0.766667
4,1005,Female,72.0,4.0,58.0,6.0,64,0,False,True,False,False,False,0.233333
5,1006,Male,95.0,9.0,88.0,10.0,94,1,False,False,True,False,False,1.000000
6,1007,Female,67.0,3.5,52.0,5.0,59,0,False,False,False,False,True,0.066667
7,1008,Male,84.0,6.5,70.0,8.0,77,1,False,False,False,True,False,0.633333
8,1009,Female,79.0,6.0,66.0,8.0,73,0,True,False,False,False,False,0.466667
9,1010,Female,93.0,8.5,82.0,10.0,90,0,False,False,True,False,False,0.933333
10,1011,Male,69.0,4.5,55.0,6.0,62,1,False,True,False,False,False,0.133333
11,1012,Male,87.0,7.8,76.0,9.0,83,1,False,False,False,False,True,0.733333
12,1013,Female,74.0,5.0,63.0,7.0,69,0,False,False,False,True,False,0.300000
13,1014,Male,90.0,8.0,85.0,9.0,88,1,True,False,False,False,False,0.833333
14,1015,Female,81.0,6.8,72.0,8.0,79,0,False,False,True,False,False,0.533333
15,1016,Male,78.0,5.8,71.0,7.0,72,1,False,False,False,False,True,0.433333
16,1017,Female,83.0,6.2,67.0,8.0,75,0,False,False,False,True,False,0.600000
17,1018,Male,86.0,7.2,73.0,8.0,82,1,True,False,False,False,False,0.700000
18,1019,Female,65.0,3.0,49.0,5.0,55,0,False,True,False,False,False,0.000000
19,1020,Male,89.0,7.5,81.0,9.0,86,1,False,False,True,False,False,0.800000
20,1021,Female,83.0,6.8,71.0,8.0,80,0,False,False,False,False,True,0.600000
21,1022,Male,71.0,4.8,59.0,6.0,66,1,False,False,False,True,False,0.200000
22,1023,Female,94.0,9.2,89.0,10.0,96,0,True,False,False,False,False,0.966667
23,1024,Male,77.0,5.2,64.0,7.0,71,1,False,False,True,False,False,0.400000
24,1025,Female,73.0,4.2,57.0,6.0,63,0,False,True,False,False,False,0.266667